function res = rgb_clamping_validator(method)
res = ischar(method) && (...
    strcmpi(method, 'Clip') || ...
    strcmpi(method, 'DeSat') || ...
    strcmpi(method, 'Greying') || ...
    strcmpi(method, 'MinUV') || ...
    strcmpi(method, 'MinItp') ...
    );
end